### ISSUE TITLE
Implement the `timeSeries` class

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/pocean-core#10]
Where do we stand with implementing the `timeSeries` class?

AFAIK, @kwilcox got it to the point of writing a netcdf file, but it was missing required metadata, correct?

@joefutrelle, are you working on that?

**Comment by rsignell-usgs** [comment]
It would be great to show a notebook of pocean working for `timeSeries` at the IOOS meeting next week (Friday, Mar 17).    We might be able to get more contributors!

**Comment by joefutrelle** [comment]
With a little guidance from @kwilcox about how to architect that code, I can work on it. The goal being to be able to use `from_dataframe` and get a bunch of reasonable global and variable attributes w/o having to construct them and pass them in.

**Comment by joefutrelle** [comment]
Looks like step 1 is implementing `nc_attributes` which is used in `to_dataframe` to populate global and per-variable attributes, a question for @kwilcox  is how much is appropriate to include in that function, it's pretty minimal in the `IncompleteMultidimensionalTrajectory` implementation. For instance should we be defaulting attributes like axis or time units to reasonable values, or should pocean stay away from that kind of behavior and have the caller pass them in?

**Comment by rsignell-usgs** [comment]
This might be a question for @cwingard as well.

**Comment by kwilcox** [comment]
`nc_attributes` was a placeholder until we can figure out the metadata problem https://github.com/pyoceans/pocean-core/issues/3. I'm going to play around with `xarray` and see if it will solve that for us and we can go from there...

**Comment by joefutrelle** [comment]
Pending adopting `xarray`, would you accept a PR where I've implemented `nc_attributes` for om timeseries? It would help me in the short term for getting stuff into ERDDAP.

**Comment by kwilcox** [comment]
absolutely!
