### ISSUE TITLE
Release and package for conda-forge

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/pocean-core#20]
The OOI-CGSN OMS++ project is using pocean-core current capabilities, and will not be using new functionality before their initial review on April 30.    

@kwilcox, @ocefpaf, and @joefutrelle , okay to create an 0.1 release and package for conda-forge?

They would like to create an `oms_env.yml` file for conda using packages from conda-forge and defaults only.

**Comment by kwilcox** [comment]
As long as its version `1.0.0`, you got it. Asking joe about the open PR before releasing though.

**Comment by joefutrelle** [comment]
Also #19 keeps bugging me when deploying in Windows

**Comment by ocefpaf** [comment]
> Also #19 keeps bugging me when deploying in Windows

I am setting up AppVeyor here and this will should up, hopefully I will be able to fix it too. (PR later today.)

**Comment by kwilcox** [comment]
Once https://github.com/pyoceans/pocean-core/pull/23 is merged we can cut 1.0.0

**Comment by ocefpaf** [comment]
@kwilcox do you want me to take care of the release or do you want to sort #24 out first? (I don't think there are any problems with the packages per se, only problems with the tests.)
