### ISSUE TITLE
Metadata serialization with Xarray

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/pocean-core#3]
If I understand `pocean` correctly the matadata is stored outside the dataframe like in https://github.com/pyoceans/pocean-core/blob/master/pocean/dsg/profile/im.py#L263-L279

If there this moves to `xarray` does it make sense to "outsource" the metadata to be taken care by `xarray` instead of keeping tracking of it manually?

If so what are the issues we expected? (I know of one at least with climatology data times.)

**Comment by rsignell-usgs** [comment]
@ocefpaf, I think this is one of the advantages of using `xarray`, that the metadata can be kept with the variables.   The [`xarray` data structures](http://xarray.pydata.org/en/stable/data-structures.html), namely `Dataset`, `DataArray`, and `Coordinates` are a better fit for our work here than `Pandas` dataframes.

**Comment by ocefpaf** [comment]
`>  I think this is one of the advantages of using `xarray`

I open this issue to discuss exactly that. It can be an advantage... But maybe we want control over that to ensure the round trip of the data is lossless.

**Comment by rsignell-usgs** [comment]
@ocefpaf , sorry I don't get it.  Can you explain a bit more?

**Comment by ocefpaf** [comment]
I am not completely sure what may all the be the implications of `xarray` but here is an example of a lossy roundtrip with `iris`:

https://github.com/SciTools/iris/issues/1769

The data was `CF-1.6` but `iris` "changed" it to `CF-1.5`. Automated tools can get confused.

In `xarray` I know that the calendar of climatological data is discarded because it cannot fit a pandas index. (As far as I know only `cf_units`+`netcdf4-python` does the right thing there, but that is a niche problem anyways and we don't need to worry about it now.)

I am not too familiar with `xarray` but any metadata that it cannot fit into its model is saved into a `dict` and can be re-used later. We need to see if that is enough for a lossless roundtrip, and by that I mean, save data that has the same metadata of the data we just read.

**Comment by rsignell-usgs** [comment]
My understanding is that unlike `iris`,  `xarray` doesn't impose any CF conventions, and allows you to do whatever you want.   So my bet is that is round-trips just fine.   But of course I agree we need to find out!

**Comment by ocefpaf** [comment]
> `xarray` doesn't impose any CF convention

That is correct but it does impose some assumptions to decode the CF based and it stores what the metadata info in its own way to encode it again when saving.

Anyways this is not a big deal we just need to find out if we want to use `xarray` to carry the metadata over or if we want to keep taking care of that internally.

**Comment by rsignell-usgs** [comment]
Ah, like the units for time, for example?  Yes, if not specified it will default, but we can control:
http://xarray.pydata.org/en/stable/io.html#writing-encoded-data
http://xarray.pydata.org/en/stable/io.html#time-units

Or am I still not understanding.

**Comment by ocefpaf** [comment]
> Or am I still not understanding?

Nope. That is it. I don't know all the details of `xarray` and this issue is just remember us to check if we won't loose any metadata in case  we decide to use it. (We can still use `xarray` and carry the metadata ourselves but that does not sound like a good idea.)

**Comment by kwilcox** [comment]
Round tripping using the `ncojson` spec is best and possible now
