### ISSUE TITLE
1.2.6 not in conda

### ISSUE THREAD

**Issue by SoftwareMonk** [pyoceans/pocean-core#30]
The latest version in conda is 1.2.5 but gutils requires at least 1.2.6

**Comment by ocefpaf** [comment]
Thanks. I just update the conda-forge package. Should be up in the channel soon.

**Comment by kwilcox** [comment]
Thanks @ocefpaf.  

@SoftwareMonk If you are brave... Travis uploads to the `axiom-data-science` channel on git tag. I'll look into automating a PR to the conda feedstock as well. Typically I'm too impatient to wait for the osx `conda-forge` build which I don't have a personal need for!

**Comment by ocefpaf** [comment]
> Typically I'm too impatient to wait for the osx conda-forge build

I made it `noarch`  and that should no longer be a problem.
