### ISSUE TITLE
Round-tripping using Pandas DataFrames

### ISSUE THREAD

**Issue by joefutrelle** [pyoceans/pocean-core#4]
To facilitate using pocean for round-tripping, e.g., converting between mututally convertible representations (e.g., between contiguous and indexed ragged array representations), it should be possible to use `to_dataframe` on the source representation's class and then pass the result to `from_dataframe` on the target representation's class and get a NetCDF file that matches the source NetCDF file as much as possible wrt attributes, variable names, etc.

**Comment by joefutrelle** [comment]
The implementation strategy could be to subclass DataFrame to carry metadata and other information necessary for round-tripping. That way callers that don't care about round-tripping could ignore all that extra information.

**Comment by kwilcox** [comment]
The `meta`/`json` interface provides a metadata object/class to use for round tripping
