### ISSUE TITLE
IncompleteMultidimensionalProfile writes a file that Xarray can't read

### ISSUE THREAD

**Issue by eldobbins** [pyoceans/pocean-core#52]
I'm trying to write several CTD casts to a single netCDF file. This would be following [NCEI_Profile_Incomplete](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/profileIncomplete.cdl). The data are in a single Pandas Dataframe.
 
I set axis to:
>    axes = {
        't': 'time',
        'x': 'longitude',
        'y': 'latitude',
        'z': 'prDM',
        'profile': 'id'
    }

Which leads to a file that dumps to:
>netcdf test {
dimensions:
	id = 47 ;
	prDM = 1523 ;
variables:
	double prDM(id, prDM) ;
		prDM:_FillValue = -9999.9 ;
		prDM:axis = "Z" ;
...

When I try and read that file with XArray - ds = xr.open_dataset(pathname) - it errors with this message:
>E  xarray.core.variable.MissingDimensionsError: 'prDM' has more than 1-dimension and the same name as one of its dimensions ('id', 'prDM'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.

I think a new dimension, z, should be created that has the values of prDM, that prDM can use as a dimension. 

The only example code I've seen that uses IncompleteMultidimensionalProfile.from_dataframe employs a loop to write separate files for each cast. Is that how it's supposed to be used?
Thanks.

**Comment by eldobbins** [comment]
I also have a related issue with the Orthogonal Profile (https://github.com/pyoceans/pocean-core/issues/51)

**Comment by kwilcox** [comment]
Can you upload a CSV file I can load into a dataframe that shows this? I'm guessing the data doesn't fit cleanly into an `IncompleteMultidimensionalProfile` but can't confirm.

**Comment by eldobbins** [comment]
I put added file: https://github.com/eldobbins/pocean-core/blob/master/pocean/tests/dsg/profile/resources/TXF18_CTD.csv

It's too big for a proper test file, but is an example of a file type we work with regularly: multiple CTD casts to different depths sequentially in the same file. 

I've been working with these files in XArray. To make the netCDF file using XArray, I make id (consecutive station number, i.e. profile) and z (copied from prDM which is pressure, i.e. depth) indices in a pd.DataFrame called data, and then say xr.Dataset.from_dataframe(data) and it magically works. I end up with 2 dimensions, and prDM(id,Z) is a variable that depends on both. If it would be helpful, I can also add code and/or the resulting netCDF file to my forked directory.

**Comment by kwilcox** [comment]
I "fixed" this here: https://github.com/pyoceans/pocean-core/commit/f031bfedd00246d8e1de99938c31fb335eeda45d. It's really a work-around for xarray's disallowance of multi-dimensional variables and dimensions sharing a name. I can't default this to `True` for backwards compat reasons (people may be assuming coordinate vars and dimensions share the same name), so you'll need to pass `unique_dims=True` as a parameter to `from_dataframe`.

I'll merge and release 1.9.0 once CI finishes up.

**Comment by kwilcox** [comment]
@eldobbins closing as this is fixed. you can test the new `unique_dims=True` for `xarray` compatibility.
