### ISSUE TITLE
Release to capture new ragged timeSeriesProfile capabilities?

### ISSUE THREAD

**Issue by rsignell-usgs** [pyoceans/pocean-core#60]
@kwilcox  could we get a new release of pocean-core, now that ragged timeSeriesProfile is working?

Here's a notebook that provides an example of an end-to-end workflow, starting from SeaBird CNV files and ending up with CF-1.7 compliant NetCDF:

https://gist.github.com/rsignell-usgs/61dc61cbd62bc0a52a6198977303ee10

**Comment by kwilcox** [comment]
1.9.3 making its way through CI: https://github.com/pyoceans/pocean-core/releases/tag/1.9.3, thanks for the reminder!
