### ISSUE TITLE
Python 2?

### ISSUE THREAD

**Issue by joefutrelle** [pyoceans/pocean-core#7]
ran into a type hint while trying to run under Python 2

https://github.com/pyoceans/pocean-core/blob/50de321357471d0b4ae484fd4e226271be26b39e/pocean/cf.py#L17

is Python 2 support desired / planned?

**Comment by kwilcox** [comment]
I wasn't planning to support anything less than py3.5 (for typing). `conda` makes it really each to install all of the dependencies on any platform with py3.5+. That being said, if someone has a tight requirement on py2 there isn't much py3 only stuff in the codebase at the moment and we could switch to supporting 2.7.

**Comment by joefutrelle** [comment]
We have a pretty firm <3.5 requirement, IIRC we will be running Debian Jessie and earlier in production.

https://wiki.debian.org/Python#Supported_Python_Versions

**Comment by kwilcox** [comment]
Again, I'm not against py2 compatibility. Just making sure we really need it.

Is it possible to use `conda` on your systems to run the software? EOL for py2 is only a few years away! http://legacy.python.org/dev/peps/pep-0373/#update

**Comment by joefutrelle** [comment]
I'm inexperienced with conda, if it can give us 3.5 on a distro where the default py3 version is lower, then we can do that.
